# Generated by Django 6.0.1 on 2026-01-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('AP', 'Approved')], default='DR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('IR', 'In Review'), ('AP', 'Approved')], default='DR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Date & time this event should be executed.', null=True)),
                ('status', models.CharField(choices=[('SC', 'Scheduled'), ('EX', 'Executed'), ('CX', 'Cancelled')], default='SC', max_length=2)),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='flighttest.testplan')),
            ],
        ),
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flighttest.requirement')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flighttest.testplan')),
            ],
        ),
    ]
