# Generated by Django 6.0.1 on 2026-01-31 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flighttest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpoint',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_points', to='flighttest.requirement'),
        ),
        migrations.AlterField(
            model_name='testpoint',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_points', to='flighttest.testplan'),
        ),
    ]
